language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t reternal-c2 .
  - docker run -e "C2_SECRET=test_build_token_c2" -d -p 127.0.0.1:8080:8080 --name reternal-c2 reternal-c2

script:
  - docker ps | grep -q reternal-c2