# empire3:
#   name: EmpireV3
#   description: NOTE DOES NOT WORK WITH PYTHON YET. Empire 3.1 is a post-exploitation framework that includes a pure-PowerShell 2.0 Windows agent, and compatibility with Python 3.x Linux/OS X agents. It is the merger of the previous PowerShell Empire and Python EmPyre projects. The framework offers cryptologically-secure communications and flexible architecture.
#   thumbnail: https://user-images.githubusercontent.com/20302208/70022749-1ad2b080-154a-11ea-9d8c-1b42632fd9f9.jpg
#   platforms:
#     - Windows
#     - macOS
#     - Linux
#   enabled: true
#   modules:
#     get: c2.modules.empire3.get
#     run: c2.modules.empire3.run
#   agents:
#     get: c2.agents.empire3.get
#     set: c2.agents.empire3.set
#   listeners:
#     get: c2.listeners.empire3.get
#     create: c2.listeners.empire3.create
#     options: c2.listeners.empire3.options
#     delete: c2.listeners.empire3.delete
#   stagers:
#     get: c2.stagers.empire3.get
#     create: c2.stagers.empire3.create
#   tasks:
#     create: c2.tasks.empire3.create

empire2:
  name: EmpireV2
  description: Empire is a post-exploitation framework that includes a pure-PowerShell2.0 Windows agent, and a pure Python 2.6/2.7 Linux/OS X agent. It is the merge of the previous PowerShell Empire and Python EmPyre projects. The framework offers cryptologically-secure communications and a flexible architecture. On the PowerShell side, Empire implements the ability to run PowerShell agents without needing powershell.exe, rapidly deployable post-exploitation modules ranging from key loggers to Mimikatz, and adaptable communications to evade network detection, all wrapped up in a usability-focused framework.
  thumbnail: https://user-images.githubusercontent.com/20302208/70022749-1ad2b080-154a-11ea-9d8c-1b42632fd9f9.jpg
  platforms:
    - Windows
    - macOS
    - Linux
  enabled: true
  modules:
    get: c2.modules.empire2.get
    run: c2.modules.empire2.run
  agents:
    get: c2.agents.empire2.get
    set: c2.agents.empire2.set
    delete: c2.agents.empire2.delete
    stop: c2.agents.empire2.stop
  listeners:
    get: c2.listeners.empire2.get
    create: c2.listeners.empire2.create
    options: c2.listeners.empire2.options
    delete: c2.listeners.empire2.delete
  stagers:
    get: c2.stagers.empire2.get
    create: c2.stagers.empire2.create
  tasks:
    create: c2.tasks.empire2.create


    
# covenant:
#   name: Covenant
#   description: Covenant is a .NET command and control framework that aims to highlight the attack surface of .NET, make the use of offensive .NET tradecraft easier, and serve as a collaborative command and control platform for red teamers. Covenant is an ASP.NET Core, cross-platform application that includes a web-based interface that allows for multi-user collaboration.
#   thumbnail: https://www.fatrodzianko.com/wp-content/uploads/2019/08/covenant-c2_create-listener.jpg
#   platforms:
#     - Windows
#   enabled: false
#   state: c2.state.empire2
#   agents:
#     get: c2.agents.covenant.get
#     set: c2.agents.covenant.set
#   listeners:
#     get: c2.listeners.covenant.get
#     set: c2.listeners.covenant.set
#   stagers:
#     get: c2.stagers.covenant.get
#     set: c2.listeners.covenant.set
#   build:
#     - name: listeners
#       description: Choose a listener that the stager will use
#       task: c2.listeners.covenant.set
#     - name: BuildStager
#       description: 'Set parameters for stager'
#       task: 'c2.stagers.covenant.set'
#     - name: 'Build stager'
#       description: 'Build stager'
#       task: 'c2.stagers.covenant.build'
      